### ISSUE TITLE
Testsuites is undefined

### ISSUE THREAD

**Issue by ghost** [amalfra/junit-cli-report-viewer#3]
I found this project on NPM and found it useful to quickly view test results. Unfortunately I get an error with a report, that has a single root testsuite. 

    TypeError: Cannot read property '$' of undefined
        at /usr/local/lib/node_modules/junit-cli-report-viewer/index.js:33:26

Your tool assumes the test report xml starts with a root node `<testsuites>`. My report starts with `<testsuite>` as root.

I've tried to find a definition for the testresult format, and was only able to find this:
https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

From the XSD I think it's valid to start with a single suite, instead of a collection of suites.
Wonder if you have any info, if both `<testsuite>` and `<testsuites>` is allowed as a root node?

I'd like to provide a fix, which also checks for `result.testsuite`, in addition to `result.testsuites`, if you're ok with that.

**Comment by ghost** [comment]
Oops, I was trying to view an excerpt. I'm working with a weird setup here.
I'll close the issue, sorry ;)

**Comment by gpaOliveira** [comment]
I can't understand why this was closed - I have exactly the same situation!
